org: unknown2024
app: planning-poker-lambdas
service: planning-poker-lambdas

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:050752607749:table/Users"
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource: "arn:aws:ssm:us-east-1:050752607749:parameter/*"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "arn:aws:sns:us-east-1:050752607749:LambdaErrorAlerts"

functions:
  hello:
    handler: lambdas/hello.handler
    events:
      - httpApi:
          path: /
          method: get

  getUser:
    handler: lambdas/get-user.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get

  getUsers:
    handler: lambdas/get-users.handler
    events:
      - httpApi:
          path: /users
          method: get

  meUser:
    handler: lambdas/me-user.handler
    events:
      - httpApi:
          path: /me-user
          method: get

  sendEmail:
    handler: lambdas/send-email.handler
    events:
      - httpApi:
          path: /send-email
          method: get

  createUser:
    handler: lambdas/create-user.handler
    events:
      - httpApi:
          path: /users
          method: post

  updateUser:
    handler: lambdas/update-user.handler
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: lambdas/delete-user.handler
    events:
      - httpApi:
          path: /users/{id}
          method: delete
